package Modelo;
// Generated 21/11/2022 02:12:41 PM by Hibernate Tools 4.3.1



/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Integer cantidad;
     private Integer precio;

    public Productos() {
    }

    public Productos(String nombre, Integer cantidad, Integer precio) {
       this.nombre = nombre;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


